# Generated by Django 5.2.13 on 2026-05-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage_herobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='banner_type',
            field=models.CharField(choices=[('MAIN', 'Main Hero'), ('NEW_ARRIVAL', 'New Arrival Section'), ('BEST_SELLER', 'Best Seller Section')], default='MAIN', max_length=20),
        ),
    ]
