# Generated by Django 5.2.13 on 2026-05-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_herobanner_banner_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Tawakkal', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('contact_email', models.EmailField(default='info@tawakkal.com', max_length=254)),
                ('contact_phone', models.CharField(default='+92 300 1234567', max_length=20)),
                ('address', models.TextField(default='Karachi, Pakistan')),
                ('facebook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram_url', models.URLField(blank=True, max_length=500, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_fee', models.IntegerField(default=250)),
                ('free_shipping_threshold', models.IntegerField(default=5000)),
                ('tax_percent', models.IntegerField(default=0)),
                ('announcement_text', models.CharField(default='Free Shipping on orders above PKR 5,000', max_length=255)),
                ('show_announcement', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.RemoveField(
            model_name='herobanner',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='left_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='right_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
