# Generated by Django 5.2.13 on 2026-05-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_remove_herobanner_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
