# Generated by Django 5.2.13 on 2026-06-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_image_category_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wholesale_package_size',
            field=models.PositiveIntegerField(default=6, help_text='Minimum number of items for wholesale package'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.CharField(blank=True, help_text='Price per item when bought in wholesale', max_length=50, null=True),
        ),
    ]
