# Generated by Django 5.2.13 on 2026-06-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tiktokreel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_sync_active',
            field=models.BooleanField(default=False, help_text='Enable automatic syncing of TikTok reels'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_username',
            field=models.CharField(blank=True, help_text='Enter your TikTok username without @', max_length=100, null=True),
        ),
    ]
