# Generated by Django 5.2.13 on 2026-06-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings_tiktok_sync_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='tiktok_username',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_profile_url',
            field=models.URLField(blank=True, help_text='Enter your TikTok profile URL (e.g., https://www.tiktok.com/@tawakkalstudio)', max_length=500, null=True),
        ),
    ]
