# Generated by Django 5.2.13 on 2026-06-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_product_price_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokreel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='tiktok/'),
        ),
        migrations.AlterField(
            model_name='tiktokreel',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
