# Generated by Django 5.2.13 on 2026-06-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_tiktok_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_embed_code',
            field=models.TextField(blank=True, help_text='Paste your TikTok feed embed code here (e.g. Elfsight, EmbedSocial, etc.)', null=True),
        ),
    ]
