# Generated by Django 5.2.13 on 2026-06-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_tiktok_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_story_image',
            field=models.ImageField(blank=True, help_text="Image for the 'Our Story' section on the homepage", null=True, upload_to='settings/'),
        ),
    ]
