# Generated by Django 5.2.13 on 2026-06-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sitesettings_about_story_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_logo',
            field=models.ImageField(blank=True, help_text='Secondary logo (for sticky mode and dark hero pages)', null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Primary logo (for light backgrounds)', null=True, upload_to='settings/'),
        ),
    ]
